#
FROM kkeene44/wrf-coop:version16
MAINTAINER Kelly Werner <kkeene@ucar.edu>

#	DO NOT CHANGE UNDERSCORE GIT STRINGS
#	THESE ARE USED FOR JENKINS TESTING

RUN git clone _GIT_URL_ WRF \
  && cd WRF \
  && git checkout _GIT_BRANCH_ \
  && cd ..

RUN git clone https://github.com/wrf-model/SCRIPTS.git SCRIPTS \
  && cp SCRIPTS/rd_l2_norm.py . && chmod 755 rd_l2_norm.py \
  && cp SCRIPTS/script.csh .    && chmod 755 script.csh    \
  && ln -sf SCRIPTS/Namelists . 

VOLUME /wrf
CMD ["/bin/tcsh"]
