#
FROM kkeene44/wrf-coop:version16
MAINTAINER Kelly Werner <kkeene@ucar.edu>

RUN git clone --recurse-submodule https://github.com/wrf-model/WRF.git WRF \
  && cd WRF \
  && git checkout release-v4.4.2 \
  && git checkout master \
  && git checkout develop \
  && git checkout release-v4.4.1 \
  && cd ..

RUN git clone https://github.com/davegill/SCRIPTS.git SCRIPTS \
  && cp SCRIPTS/rd_l2_norm.py . && chmod 755 rd_l2_norm.py \
  && cp SCRIPTS/script.csh .    && chmod 755 script.csh    \
  && ln -sf SCRIPTS/Namelists . 

VOLUME /wrf
CMD ["/bin/tcsh"]
